// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_4XTniw9aw941nGsTvEqJ0XWnE5R0po8',
    appId: '1:328672234249:web:4cd2e23f918b25a66621d8',
    messagingSenderId: '328672234249',
    projectId: 'chat-app-ab57f',
    authDomain: 'chat-app-ab57f.firebaseapp.com',
    storageBucket: 'chat-app-ab57f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrW7deKIG2SREr9-UVmsFfl7THRva0dWo',
    appId: '1:328672234249:android:d1896e47f3c0f85d6621d8',
    messagingSenderId: '328672234249',
    projectId: 'chat-app-ab57f',
    storageBucket: 'chat-app-ab57f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQYVhfE0jOZ1zkCzlnRNe0p9hk_vcQB7o',
    appId: '1:328672234249:ios:f1324370aa5929616621d8',
    messagingSenderId: '328672234249',
    projectId: 'chat-app-ab57f',
    storageBucket: 'chat-app-ab57f.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQYVhfE0jOZ1zkCzlnRNe0p9hk_vcQB7o',
    appId: '1:328672234249:ios:f1324370aa5929616621d8',
    messagingSenderId: '328672234249',
    projectId: 'chat-app-ab57f',
    storageBucket: 'chat-app-ab57f.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_4XTniw9aw941nGsTvEqJ0XWnE5R0po8',
    appId: '1:328672234249:web:cb55d5d6e621b6436621d8',
    messagingSenderId: '328672234249',
    projectId: 'chat-app-ab57f',
    authDomain: 'chat-app-ab57f.firebaseapp.com',
    storageBucket: 'chat-app-ab57f.firebasestorage.app',
  );
}
